import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../../supabaseClient.js';
import { COLORS as C } from '../../theme.js';
import { Plus, Eye, Heart, Send, Trash2 } from 'lucide-react';
import { EngagementList } from '../../components/EngagementList.jsx';

export function StoriesTab({ id, onOpenProfile }) {
  const [stories,setStories]=useState([]); const [loading,setLoading]=useState(true); const [caption,setCaption]=useState(''); const [creating,setCreating]=useState(false); const [selected,setSelected]=useState(null); const [engagement,setEngagement]=useState(null); const [counts,setCounts]=useState({});
  const load=async()=>{ setLoading(true); const {data}=await supabase.from('stories').select('id,author_id,media_url,media_type,caption,background,visibility,expires_at,created_at,profiles:author_id(display_name,handle,avatar_url,flag)').gt('expires_at',new Date().toISOString()).is('deleted_at',null).order('created_at',{ascending:false}).limit(80); setStories(data||[]); setLoading(false); };
  const loadCounts=async(storyId)=>{ const [{count:views},{count:likes}] = await Promise.all([supabase.from('story_views').select('viewer_id',{count:'exact',head:true}).eq('story_id',storyId), supabase.from('story_reactions').select('user_id',{count:'exact',head:true}).eq('story_id',storyId)]); setCounts(prev=>({...prev,[storyId]:{views:views ?? 0, likes:likes ?? 0}})); };
  useEffect(()=>{ stories.filter(s=>s.author_id===id).forEach(s=>loadCounts(s.id)); },[stories,id]);
  useEffect(()=>{load(); const ch=supabase.channel('stories_live').on('postgres_changes',{event:'*',schema:'public',table:'stories'},load).subscribe(); return()=>supabase.removeChannel(ch);},[]);
  const mine=useMemo(()=>stories.filter(s=>s.author_id===id),[stories,id]);
  const create=async()=>{if(!caption.trim()||!id)return;setCreating(true);await supabase.from('stories').insert({author_id:id,media_type:'text',caption:caption.trim(),visibility:'public'});setCaption('');setCreating(false);load();};
  const react=async(s)=>{if(!id)return;await supabase.from('story_reactions').upsert({story_id:s.id,user_id:id,reaction:'❤️'});await supabase.rpc('record_story_view',{p_story_id:s.id});if(s.author_id===id)loadCounts(s.id);else setCounts(prev=>({...prev,[s.id]:{...prev[s.id],likes:(prev[s.id]?.likes||0)+1}}));};
  const remove=async(s)=>{if(s.author_id!==id)return;await supabase.from('stories').update({deleted_at:new Date().toISOString()}).eq('id',s.id);setSelected(null);load();};
  return <div className="space-y-4">
    <div className="flex items-center justify-between"><div><h2 className="text-xl font-bold" style={{color:C.ivory}}>Stories</h2><p className="text-xs" style={{color:C.muted}}>24 h · privé, public et cercle proche · réactions · vues</p></div></div>
    <div className="rounded-2xl p-4 border" style={{background:C.surface,borderColor:C.border}}><textarea value={caption} onChange={e=>setCaption(e.target.value)} placeholder="Créer une story texte…" className="w-full bg-transparent outline-none min-h-20" style={{color:C.ivory}}/><div className="flex justify-end"><button disabled={creating||!caption.trim()} onClick={create} className="px-4 py-2 rounded-xl font-semibold" style={{background:C.gold,color:'#000'}}><Plus size={16} className="inline mr-1"/>Publier</button></div></div>
    {loading?<p style={{color:C.muted}}>Chargement…</p>:<div className="grid grid-cols-2 sm:grid-cols-4 gap-3">{stories.map(s=><button key={s.id} onClick={async()=>{setSelected(s);await supabase.rpc('record_story_view',{p_story_id:s.id});if(s.author_id===id)loadCounts(s.id);}} className="text-left rounded-2xl overflow-hidden border min-h-48 p-3 flex flex-col justify-between" style={{background:s.background||C.surface,borderColor:C.border,color:C.ivory}}><div><b>{s.profiles?.display_name||'Membre'}</b><div className="text-xs opacity-70">@{s.profiles?.handle||''}</div></div><p className="text-sm line-clamp-5">{s.caption}</p><div className="text-[10px] opacity-60 flex items-center justify-between gap-2"><span>24 h · {new Date(s.created_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</span>{s.author_id===id&&<span>👁 {counts[s.id]?.views||0} · ❤️ {counts[s.id]?.likes||0}</span>}</div></button>)}</div>}
    {selected&&<div className="fixed inset-0 z-50 flex items-center justify-center p-4" style={{background:'rgba(0,0,0,.82)'}}><div className="w-full max-w-md rounded-3xl p-5" style={{background:C.surface,color:C.ivory}}><div className="flex justify-between"><b>{selected.profiles?.display_name||'Story'}</b><button onClick={()=>setSelected(null)}>✕</button></div><p className="text-lg py-12 whitespace-pre-wrap">{selected.caption}</p><div className="flex gap-2 flex-wrap">{selected.author_id===id&&<><button onClick={()=>setEngagement({type:'storyViews',id:selected.id})} className="px-3 py-2 rounded-xl border text-xs">👁 Voir les vues</button><button onClick={()=>setEngagement({type:'storyLikes',id:selected.id})} className="px-3 py-2 rounded-xl border text-xs">❤️ Voir les likes</button></>}<button onClick={()=>react(selected)} className="px-3 py-2 rounded-xl border"><Heart size={16}/></button><button className="px-3 py-2 rounded-xl border"><Send size={16}/></button>{selected.author_id===id&&<button onClick={()=>remove(selected)} className="px-3 py-2 rounded-xl border text-red-400"><Trash2 size={16}/></button>}<span className="ml-auto text-xs opacity-60 flex items-center gap-1"><Eye size={14}/> {counts[selected.id]?.views||0} vues · ❤️ {counts[selected.id]?.likes||0}</span></div></div></div>}
    {engagement&&<EngagementList type={engagement.type} targetId={engagement.id} ownerId={selected?.author_id || id} viewerId={id} onClose={()=>setEngagement(null)}/>} 
  </div>;
}
export default StoriesTab;
