import { useEffect, useMemo, useState } from "react";
import { useTranslation } from "react-i18next";
import { supabase } from "../../supabaseClient.js";
import { formatAmount } from "../../lib/paymentProvider.js";
import { Banknote, BarChart3, Gift, Megaphone, ShoppingBag, Sparkles, WalletCards, ArrowUpRight, Clock3, ShieldCheck } from "lucide-react";
import { MonetizationPanel } from "./MonetizationPanel.jsx";
const SOURCES={ads:["Publicité",Megaphone],tips:["Pourboires",Gift],subscriptions:["Abonnements",Sparkles],marketplace:["Ventes",ShoppingBag],campaigns:["Campagnes",BarChart3],referrals:["Parrainage",ArrowUpRight],bonus:["Bonus BAARO",Banknote]};
const money=(v,c)=>formatAmount(Number(v||0)/100,c||"XOF");
export function EconomyTab({id}){
 const { t } = useTranslation();
 const [dashboard,setDashboard]=useState(null),[busy,setBusy]=useState(false),[notice,setNotice]=useState(""),[payout,setPayout]=useState({amount:"",method:"mobile_money"});
 async function load(){if(!id)return;const [{data,error},{data:rewardData}]=await Promise.all([supabase.rpc("get_economy_dashboard"),supabase.rpc("get_creator_rewards_summary")]);if(error)setNotice("Le tableau des revenus est temporairement indisponible.");else setDashboard(data||null);setRewards(rewardData||null)}
 useEffect(()=>{load();const params=new URLSearchParams(window.location.search);const state=params.get("payment");if(state==='success')setPaymentFeedback("Paiement confirmé : le fournisseur va confirmer définitivement la commande.");if(state==='cancelled')setPaymentFeedback("Paiement annulé.");if(state==='return')setPaymentFeedback("Retour du paiement reçu. La confirmation finale arrive après le webhook fournisseur.")},[id]);
 const currency=dashboard?.currency||"XOF",sources=useMemo(()=>dashboard?.by_source||[],[dashboard]);
 async function toggle(){setBusy(true);setNotice("");const {error}=await supabase.rpc("set_creator_monetization_enabled",{p_enabled:!Boolean(dashboard?.monetization?.enabled)});if(error)setNotice("Impossible de modifier la monétisation maintenant.");else await load();setBusy(false)}
 async function request(){const amount=Number(payout.amount);if(!Number.isFinite(amount)||amount<=0){setNotice("Indiquez un montant de retrait valide.");return}if(payout.method==='mobile_money' && !/^\d{6,15}$/.test(String(payout.phone).replace(/\D/g,''))){setNotice("Indiquez un numéro Mobile Money valide.");return}setBusy(true);setNotice("");try{const session=(await supabase.auth.getSession()).data?.session;if(!session?.access_token)throw new Error("Session requise.");const base=(import.meta.env.VITE_API_BASE_URL||"").replace(/\/$/,"");const res=await fetch(`${base}/api/payouts`,{method:"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({amount,method:payout.method,destination:{prefix:String(payout.prefix).replace(/\D/g,''),phone:String(payout.phone).replace(/\D/g,'')}})});const d=await res.json().catch(()=>({}));if(!res.ok)throw new Error(d?.error||"Retrait impossible.");setNotice(d.status==='processing'?"Retrait placé en traitement. Le fournisseur confirmera le paiement automatiquement.":"Demande de retrait enregistrée.");setPayout({amount:"",method:"mobile_money",prefix:"223",phone:""});await load()}catch(error){const m=String(error.message||"");setNotice(m.includes("MIN_CASHOUT")?"Le minimum de retrait n'est pas atteint.":m.includes("PAYOUT_KYC_REQUIRED")?"Vérification KYC requise avant tout retrait.":m)}finally{setBusy(false)}}
 if(!id)return <div className="rounded-2xl border border-white/10 bg-white/[.03] p-6 text-sm text-white/60">Connectez-vous pour accéder à vos revenus.</div>;
 return <section className="space-y-5 pb-8">
  <MonetizationPanel />
  <div className="rounded-2xl border border-amber-300/15 bg-amber-300/[.04] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-xs font-bold uppercase tracking-[.16em] text-amber-300">BAARO Creator Rewards</div><div className="mt-1 text-lg font-black text-white">{Number(rewards?.points||0).toLocaleString("fr-FR")} points</div><p className="text-xs text-white/45">Points de performance non monétaires : ils ne sont ni encaissables ni transférables.</p></div><div className="text-right"><div className="text-xs text-white/40">Niveau</div><div className="font-bold text-amber-200">{rewards?.tier||"starter"}</div><div className="text-[11px] text-white/35">Prochain : {rewards?.next_tier||"rising"} · {Number(rewards?.next_threshold||5000).toLocaleString("fr-FR")} pts</div></div></div></div>
  <header className="rounded-3xl border border-emerald-300/15 bg-gradient-to-br from-emerald-300/[.10] via-white/[.03] to-transparent p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-300">BAARO Economy</p><h1 className="mt-1 text-2xl font-black text-white">Créez de la valeur. Gagnez ensemble.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-white/55">Vos revenus sont calculés côté serveur, séparés des crypto-actifs et conservés dans un registre auditable. Le navigateur ne peut pas modifier votre solde.</p></div><div className="rounded-2xl border border-white/10 bg-black/20 p-4 min-w-[180px]"><div className="text-xs text-white/45">{t("economy.available")}</div><div className="mt-1 text-2xl font-black text-white">{money(dashboard?.available_minor,currency)}</div><div className="mt-1 text-xs text-white/40">En attente : {money(dashboard?.pending_minor,currency)}</div></div></div></header>
  {paymentFeedback&&<div className="rounded-xl border border-sky-300/20 bg-sky-300/5 px-3 py-2 text-xs text-sky-100">{paymentFeedback}</div>}
  {notice&&<div className="rounded-xl border border-amber-300/20 bg-amber-300/5 px-3 py-2 text-xs text-amber-100">{notice}</div>}
  <div className="grid gap-3 sm:grid-cols-3">{[[t("economy.available"),dashboard?.available_minor],[t("economy.payout_hold"),dashboard?.payout_hold_minor],[t("economy.paid_out"),dashboard?.paid_out_minor]].map(([l,v])=><div key={l} className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="text-xs text-white/45">{l}</div><div className="mt-1 text-lg font-bold text-white">{money(v,currency)}</div></div>)}</div>
  <div className="grid gap-4 lg:grid-cols-[1.3fr_.7fr]"><div className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-bold text-white">D'où viennent vos revenus ?</h2><p className="text-xs text-white/40">Montants nets de la part BAARO définie côté serveur.</p></div><BarChart3 size={18} className="text-emerald-300"/></div><div className="space-y-2">{!sources.length&&<p className="text-sm text-white/40">Publiez, vendez ou développez votre audience pour commencer.</p>}{sources.map(r=>{const [l,I]=SOURCES[r.source]||[r.source,Banknote];return <div key={r.source} className="flex items-center gap-3 rounded-xl bg-white/[.025] p-3"><span className="rounded-lg bg-emerald-300/10 p-2 text-emerald-300"><I size={16}/></span><span className="flex-1 text-sm text-white/75">{l}</span><span className="font-semibold text-white">{money(r.net_minor,currency)}</span></div>})}</div></div>
   <div className="space-y-4"><div className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 text-emerald-300" size={20}/><div><h2 className="font-bold text-white">Monétisation créateur</h2><p className="mt-1 text-xs leading-5 text-white/45">Éligibilité aux revenus publicitaires, pourboires, abonnements et campagnes. Les taux restent contrôlés par BAARO.</p></div></div><button onClick={toggle} disabled={busy} className="mt-4 w-full rounded-xl bg-white/10 px-4 py-2.5 text-sm font-bold text-white hover:bg-white/15 disabled:opacity-50">{dashboard?.monetization?.enabled?"Désactiver":"Activer la monétisation"}</button></div>
    <div className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="flex items-center gap-2"><WalletCards size={18} className="text-emerald-300"/><h2 className="font-bold text-white">Retirer mes revenus</h2></div><p className="mt-1 text-xs text-white/40">{t("economy.minimum")} : {money(dashboard?.min_cashout_minor,currency)} · contrôles anti-fraude/KYC si requis.</p><input value={payout.amount} onChange={e=>setPayout(p=>({...p,amount:e.target.value}))} inputMode="decimal" placeholder={`Montant (${currency})`} className="mt-3 w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 text-sm text-white outline-none"/><select value={payout.method} onChange={e=>setPayout(p=>({...p,method:e.target.value}))} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-3 py-2.5 text-sm text-white"><option value="mobile_money">Mobile Money</option><option value="bank_transfer">Virement bancaire</option></select><div className="mt-2 grid grid-cols-[80px_1fr] gap-2"><input value={payout.prefix} onChange={e=>setPayout(p=>({...p,prefix:e.target.value}))} inputMode="numeric" placeholder="223" className="rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-sm text-white"/><input value={payout.phone} onChange={e=>setPayout(p=>({...p,phone:e.target.value}))} inputMode="tel" placeholder="Numéro Mobile Money" className="rounded-xl border border-white/10 bg-black/20 px-3 py-2 text-sm text-white"/></div><p className="mt-2 text-[10px] leading-4 text-white/35">Le retrait est bloqué tant que le profil KYC n’est pas vérifié. Le numéro est transmis au fournisseur de payout sécurisé.</p><button onClick={request} disabled={busy} className="mt-2 w-full rounded-xl bg-emerald-400 px-4 py-2.5 text-sm font-black text-black disabled:opacity-50">Demander le paiement</button></div>
   </div></div>
  <div className="rounded-2xl border border-white/10 bg-white/[.025] p-4"><div className="flex items-center gap-2"><Clock3 size={17} className="text-white/50"/><h2 className="font-bold text-white">Derniers revenus</h2></div><div className="mt-3 space-y-2">{(dashboard?.recent||[]).map(r=><div key={r.id} className="flex items-center gap-3 rounded-xl border border-white/5 p-3"><div className="flex-1"><div className="text-sm font-medium text-white">{SOURCES[r.source]?.[0]||r.source}</div><div className="text-[11px] text-white/35">{new Date(r.created_at).toLocaleString()}</div></div><div className="text-sm font-bold text-emerald-300">+{money(r.net_minor,currency)}</div></div>)}{!(dashboard?.recent||[]).length&&<p className="text-sm text-white/35">Aucune opération pour le moment.</p>}</div></div>
 </section>;
}
