/// <reference types="vite/client" />
// Dictionnaires FR/EN/AR/BM + lecture de locales/<langue>.json

// Traductions de l'écran Réglages lues dans locales/<langue>.json (section "settings").
// Toute clé absente retombe sur le dictionnaire interne, puis sur le français.
export const LOCALE_FILES = import.meta.glob("../../../locales/*.json", { eager: true }) as Record<string, any>;
export function localeSettings(code: string): Record<string, string> | null {
  const mod = LOCALE_FILES[`../../../locales/${code}.json`];
  const data = mod?.default ?? mod;
  return data && typeof data.settings === "object" ? data.settings : null;
}

export const STRINGS: Record<string, Record<string, string>> = {
  fr: {
    title: "Réglages",
    subtitle_connected: "Compte connecté",
    subtitle_local: "Préférences locales",
    search_placeholder: "Rechercher un réglage…",
    no_results: "Aucun réglage ne correspond.",
    appearance: "Apparence",
    theme: "Thème",
    theme_midnight: "Nuit",
    theme_oled: "OLED",
    theme_emerald: "Émeraude",
    language: "Langue de l'interface",
    region: "Région & paiements",
    region_desc: "Pays et devise pour Mobile Money (CinetPay) et contenus locaux.",
    country: "Pays",
    currency: "Devise préférée",
    data_network: "Données & réseau",
    data_network_desc: "Optimisé pour 2G/3G et forfaits limités.",
    performance_section: "Performance & innovation",
    performance_desc: "Contrôlez vitesse, batterie, préchargement, cache et intelligence locale.",
    smart_prefetch: "Préchargement intelligent",
    smart_prefetch_desc: "Précharge uniquement ce qui est probablement utile.",
    battery_saver: "Mode batterie",
    battery_saver_desc: "Réduit les animations et traitements en arrière-plan.",
    low_bandwidth_mode: "Mode réseau faible",
    low_bandwidth_mode_desc: "Priorise le texte et compresse davantage les médias.",
    local_cache: "Cache local intelligent",
    local_cache_desc: "Conserve temporairement les contenus utiles hors ligne.",
    privacy_ai: "IA privée par défaut",
    privacy_ai_desc: "Privilégie les traitements locaux lorsque disponibles.",
    data_saver: "Mode économie de données",
    data_saver_desc: "Moins de préchargement, images légères",
    autoplay_video: "Lecture auto des vidéos",
    autoplay_video_desc: "Désactiver pour économiser le forfait",
    offline_sync: "Sync hors-ligne prioritaire",
    offline_sync_desc: "File d'actions quand le réseau revient",
    ai_section: "Assistant IA régional",
    ai_section_desc: "Routage multi-fournisseurs selon la région.",
    ai_region: "Région IA",
    ai_auto: "Auto (selon pays)",
    ai_west_africa: "Afrique de l'Ouest",
    ai_global: "Global",
    ai_suggest: "Suggestions IA dans le fil",
    ai_suggest_desc: "Idées de posts et résumés",
    translate_section: "Traduction",
    translate_section_desc: "Fil et médias dans votre langue.",
    auto_translate: "Traduction automatique du fil",
    auto_translate_desc: "Afficher le contenu dans ma langue",
    translate_media: "Traduction média / sous-titres",
    translate_media_desc: "Vidéos et médias disponibles",
    content_section: "Contenu & communauté",
    content_section_desc: "Priorité débats et contenu local.",
    prefer_debates: "Mettre en avant les débats",
    prefer_debates_desc: "Salles et votes en premier",
    prefer_local: "Contenu de ma région d'abord",
    prefer_local_desc: "Découverte par pays",
    privacy: "Confidentialité & sécurité",
    private_profile: "Profil privé",
    private_profile_desc: "Masquer des recherches publiques",
    block_screenshots: "Bloquer les captures",
    block_screenshots_desc: "Capacitor Android",
    biometric: "Biométrie",
    a11y: "Accessibilité",
    large_text: "Texte agrandi",
    large_text_desc: "Lecture plus confortable",
    reduce_motion: "Réduire les animations",
    reduce_motion_desc: "Moins de transitions",
    profile_section: "Profil",
    edit_profile: "Modifier le profil",
    save_profile: "Enregistrer",
    cancel: "Annuler",
    display_name: "Nom affiché",
    first_name: "Prénom",
    last_name: "Nom de famille",
    birth_date: "Date de naissance",
    location: "Localisation",
    account_email: "E-mail du compte",
    account_phone: "Téléphone du compte",
    registered_country: "Pays d'inscription",
    current_country: "Pays actuel",
    country_change_wait: "Le changement de pays sera disponible après 4 mois.",
    country_change_ready: "Vous pouvez changer votre pays actuel.",
    flag_emoji: "Drapeau (emoji)",
    bio: "Bio",
    profile_saved: "✅ Profil mis à jour",
    profile_error: "❌ Impossible d'enregistrer le profil",
    secure_account: "Sécuriser mon compte",
    secure_account_desc:
      "Compte invité : ajoutez un e-mail ou un réseau social pour conserver points et historique.",
    email: "E-mail",
    password: "Mot de passe",
    secure_with_email: "Sécuriser avec cet e-mail",
    link_google: "Lier Google",
    link_facebook: "Lier Facebook",
    login_existing: "Se connecter à ce compte existant",
    forgot_password: "Mot de passe oublié ?",
    reset_sent: "✅ E-mail de réinitialisation envoyé.",
    secure_check_mail:
      "✅ Vérifiez votre boîte mail pour confirmer l'adresse.",
    privacy_policy: "Politique de confidentialité",
    privacy_body:
      "BAARO traite les données nécessaires au compte, au fil, aux notifications. Vous pouvez demander la suppression de votre compte. Les préférences de cet écran restent sur l'appareil et, si connecté, dans user_settings.",
    privacy_back: "Retour aux réglages",
    reset_prefs: "Réinitialiser les préférences",
    reset_confirm: "Remettre tous les réglages aux valeurs par défaut ?",
    reset_done: "✅ Préférences réinitialisées",
    export_prefs: "Exporter les préférences",
    import_prefs: "Importer les préférences",
    export_done: "✅ Fichier téléchargé",
    import_done: "✅ Préférences importées",
    import_error: "❌ Fichier invalide",
    copy_prefs: "Copier le JSON",
    copy_done: "✅ Copié dans le presse-papiers",
    mfa_section: "Double authentification (2FA)",
    mfa_desc:
      "Statut TOTP / SMS côté Supabase Auth. L'activation complète se fait dans le flux de sécurité du compte.",
    mfa_enabled: "2FA activée",
    mfa_disabled: "2FA non activée",
    mfa_factors: "facteur(s) vérifié(s)",
    mfa_loading: "Vérification…",
    mfa_guest: "Connectez un compte stable pour gérer la 2FA.",
    lang_partial_hint:
      "Les langues locales orientent le contenu ; l'interface reste FR/EN/AR/BM pour l'instant.",
    sessions_section: "Sessions actives",
    sessions_desc: "Appareil actuel et déconnexion globale (tous les appareils).",
    session_current: "Session actuelle",
    session_device: "Appareil",
    session_expires: "Expire",
    session_unknown: "Inconnu",
    logout_all: "Déconnecter tous les appareils",
    logout_all_confirm:
      "Déconnecter ce compte sur tous les appareils ? Vous devrez vous reconnecter partout.",
    logout_all_done: "✅ Toutes les sessions ont été fermées",
    delete_account: "Supprimer mon compte",
    delete_account_desc:
      "Action irréversible. Vos données profil / préférences locales seront effacées ; la suppression serveur dépend de la configuration Supabase.",
    delete_confirm_1:
      "Supprimer définitivement votre compte BAARO ? Cette action est irréversible.",
    delete_confirm_2:
      "Dernière confirmation : tapez SUPPRIMER pour confirmer (ou OK dans la boîte de dialogue).",
    delete_done: "✅ Compte déconnecté et données locales effacées",
    delete_error: "❌ Impossible de supprimer le compte côté serveur",
    replay_onboarding: "Revoir l'introduction BAARO",
    logout: "Se déconnecter",
    logout_confirm: "Voulez-vous vraiment vous déconnecter ?",
    guest: "Invité",
    vs_competitors: "Conçu pour l'Afrique & les marchés émergents",
    version: "Version",
    notifications_section: "Notifications",
    notifications_desc: "Contrôlez les alertes, les sons et les préférences push.",
    sound_settings: "Son des notifications",
    sound_settings_desc: "Volume, activation et test des sons de notification.",
    biometric_desc: "Authentification biométrique",
    handle_label: "Identifiant",
    choose_country: "Choisir un pays",
    contacts_links: "Coordonnées et réseaux",
    lang_beta_hint: "Bêta : ces traductions sont en cours de validation par des locuteurs. Certains textes peuvent être inexacts.",
    beta_badge: "bêta",
    theme_light: "Clair",
    theme_sunset: "Coucher",
    theme_ocean: "Océan",
    theme_forest: "Forêt",
    theme_desert: "Désert",
    theme_custom: "Perso + image",
    custom_bg: "Couleur de fond",
    custom_accent: "Couleur accent",
    custom_image: "Image de fond",
    custom_upload: "Choisir une image",
    custom_remove: "Retirer l'image",
    custom_image_too_big: "❌ Image trop lourde (10 Mo maximum).",
    custom_image_login: "❌ Connecte-toi pour envoyer une image.",
    custom_image_invalid: "❌ Fichier image invalide.",
    push_title: "Push",
    prefs_title: "Préférences",
  },
  en: {
    title: "Settings",
    subtitle_connected: "Signed in",
    subtitle_local: "Local preferences",
    search_placeholder: "Search a setting…",
    no_results: "No matching settings.",
    appearance: "Appearance",
    theme: "Theme",
    theme_midnight: "Midnight",
    theme_oled: "OLED",
    theme_emerald: "Emerald",
    language: "Interface language",
    region: "Region & payments",
    region_desc: "Country and currency for Mobile Money and local content.",
    country: "Country",
    currency: "Preferred currency",
    data_network: "Data & network",
    data_network_desc: "Built for 2G/3G and limited plans.",
    data_saver: "Data saver mode",
    data_saver_desc: "Less preload, lighter images",
    autoplay_video: "Autoplay videos",
    autoplay_video_desc: "Turn off to save data",
    offline_sync: "Priority offline sync",
    offline_sync_desc: "Action queue when network returns",
    ai_section: "Regional AI assistant",
    ai_section_desc: "Multi-provider routing by region.",
    ai_region: "AI region",
    ai_auto: "Auto (by country)",
    ai_west_africa: "West Africa",
    ai_global: "Global",
    ai_suggest: "AI suggestions in feed",
    ai_suggest_desc: "Post ideas and summaries",
    translate_section: "Translation",
    translate_section_desc: "Feed and media in your language.",
    auto_translate: "Auto-translate feed",
    auto_translate_desc: "Show content in my language",
    translate_media: "Media translation / captions",
    translate_media_desc: "Videos and media when available",
    content_section: "Content & community",
    content_section_desc: "Prioritize debates and local content.",
    prefer_debates: "Highlight debates",
    prefer_debates_desc: "Rooms and votes first",
    prefer_local: "Regional content first",
    prefer_local_desc: "Discovery by country",
    privacy: "Privacy & security",
    private_profile: "Private profile",
    private_profile_desc: "Hide from public search",
    block_screenshots: "Block screenshots",
    block_screenshots_desc: "Capacitor Android",
    biometric: "Biometrics",
    biometric_desc: "Biometric authentication",
    a11y: "Accessibility",
    large_text: "Larger text",
    large_text_desc: "Easier reading",
    reduce_motion: "Reduce motion",
    reduce_motion_desc: "Fewer animations",
    profile_section: "Profile",
    edit_profile: "Edit profile",
    save_profile: "Save",
    cancel: "Cancel",
    display_name: "Display name",
    account_email: "Account email",
    account_phone: "Account phone",
    flag_emoji: "Flag (emoji)",
    bio: "Bio",
    profile_saved: "✅ Profile updated",
    profile_error: "❌ Could not save profile",
    secure_account: "Secure my account",
    secure_account_desc:
      "Guest account: add email or social login to keep points and history.",
    email: "Email",
    password: "Password",
    secure_with_email: "Secure with this email",
    link_google: "Link Google",
    link_facebook: "Link Facebook",
    login_existing: "Sign in to this existing account",
    forgot_password: "Forgot password?",
    reset_sent: "✅ Reset email sent.",
    secure_check_mail: "✅ Check your inbox to confirm the address.",
    privacy_policy: "Privacy policy",
    privacy_body:
      "BAARO processes data needed for account, feed, notifications. You may request account deletion. Preferences on this screen stay on device and, if signed in, in user_settings.",
    privacy_back: "Back to settings",
    reset_prefs: "Reset preferences",
    reset_confirm: "Reset all settings to defaults?",
    reset_done: "✅ Preferences reset",
    export_prefs: "Export preferences",
    import_prefs: "Import preferences",
    export_done: "✅ File downloaded",
    import_done: "✅ Preferences imported",
    import_error: "❌ Invalid file",
    copy_prefs: "Copy JSON",
    copy_done: "✅ Copied to clipboard",
    mfa_section: "Two-factor authentication (2FA)",
    mfa_desc:
      "TOTP / SMS status from Supabase Auth. Full enrollment is done in the account security flow.",
    mfa_enabled: "2FA enabled",
    mfa_disabled: "2FA not enabled",
    mfa_factors: "verified factor(s)",
    mfa_loading: "Checking…",
    mfa_guest: "Sign in with a stable account to manage 2FA.",
    lang_partial_hint:
      "Local languages guide content preference; UI stays FR/EN/AR/BM for now.",
    sessions_section: "Active sessions",
    sessions_desc: "Current device and global sign-out (all devices).",
    session_current: "Current session",
    session_device: "Device",
    session_expires: "Expires",
    session_unknown: "Unknown",
    logout_all: "Sign out all devices",
    logout_all_confirm:
      "Sign out this account on every device? You will need to sign in again everywhere.",
    logout_all_done: "✅ All sessions closed",
    delete_account: "Delete my account",
    delete_account_desc:
      "Irreversible. Local profile/preferences are cleared; server deletion depends on Supabase setup.",
    delete_confirm_1:
      "Permanently delete your BAARO account? This cannot be undone.",
    delete_confirm_2:
      "Final confirmation: type DELETE to confirm (or OK in the dialog).",
    delete_done: "✅ Signed out and local data cleared",
    delete_error: "❌ Could not delete account on the server",
    replay_onboarding: "Replay BAARO intro",
    logout: "Sign out",
    logout_confirm: "Do you really want to sign out?",
    guest: "Guest",
    vs_competitors: "Built for Africa & emerging markets",
    version: "Version",
    notifications_section: "Notifications",
    notifications_desc: "Control alerts, sounds, and push preferences.",
    sound_settings: "Notification sounds",
    sound_settings_desc: "Volume, enable, and test notification sounds.",
    performance_section: "Performance & innovation",
    performance_desc: "Control speed, battery, preloading, cache and on-device intelligence.",
    smart_prefetch: "Smart preloading",
    smart_prefetch_desc: "Only preloads what is likely to be useful.",
    battery_saver: "Battery saver",
    battery_saver_desc: "Reduces animations and background work.",
    low_bandwidth_mode: "Low-bandwidth mode",
    low_bandwidth_mode_desc: "Prioritizes text and compresses media further.",
    local_cache: "Smart local cache",
    local_cache_desc: "Temporarily keeps useful content available offline.",
    privacy_ai: "Private AI by default",
    privacy_ai_desc: "Prefers on-device processing when available.",
    first_name: "First name",
    last_name: "Last name",
    birth_date: "Date of birth",
    location: "Location",
    registered_country: "Registration country",
    current_country: "Current country",
    country_change_wait: "Country change will be available after 4 months.",
    country_change_ready: "You can change your current country.",
    handle_label: "Username",
    choose_country: "Choose a country",
    contacts_links: "Contacts & links",
    lang_beta_hint: "Beta: these translations are being validated by native speakers. Some texts may be inaccurate.",
    beta_badge: "beta",
    theme_light: "Light",
    theme_sunset: "Sunset",
    theme_ocean: "Ocean",
    theme_forest: "Forest",
    theme_desert: "Desert",
    theme_custom: "Custom + image",
    custom_bg: "Background",
    custom_accent: "Accent color",
    custom_image: "Background image",
    custom_upload: "Pick image",
    custom_remove: "Remove image",
    custom_image_too_big: "❌ Image too large (10 MB max).",
    custom_image_login: "❌ Sign in to upload an image.",
    custom_image_invalid: "❌ Invalid image file.",
    push_title: "Push",
    prefs_title: "Preferences",
  },
  ar: {
    title: "الإعدادات",
    subtitle_connected: "مسجّل الدخول",
    subtitle_local: "تفضيلات محلية",
    search_placeholder: "ابحث عن إعداد…",
    no_results: "لا توجد إعدادات مطابقة.",
    appearance: "المظهر",
    theme: "السمة",
    theme_midnight: "ليلي",
    theme_oled: "OLED",
    theme_emerald: "زمردي",
    language: "لغة الواجهة",
    region: "المنطقة والمدفوعات",
    region_desc: "البلد والعملة للدفع والمحتوى المحلي.",
    country: "البلد",
    currency: "العملة المفضلة",
    data_network: "البيانات والشبكة",
    data_network_desc: "مُحسَّن لشبكات 2G/3G.",
    data_saver: "وضع توفير البيانات",
    data_saver_desc: "تحميل أقل وصور أخف",
    autoplay_video: "تشغيل تلقائي للفيديو",
    autoplay_video_desc: "عطّله لتوفير الباقة",
    offline_sync: "مزامنة دون اتصال أولاً",
    offline_sync_desc: "قائمة إجراءات عند عودة الشبكة",
    ai_section: "مساعد ذكاء اصطناعي إقليمي",
    ai_section_desc: "توجيه متعدد المزودين حسب المنطقة.",
    ai_region: "منطقة الذكاء الاصطناعي",
    ai_auto: "تلقائي (حسب البلد)",
    ai_west_africa: "غرب أفريقيا",
    ai_global: "عالمي",
    ai_suggest: "اقتراحات الذكاء في الخلاصة",
    ai_suggest_desc: "أفكار منشورات وملخصات",
    translate_section: "الترجمة",
    translate_section_desc: "الخلاصة والوسائط بلغتك.",
    auto_translate: "ترجمة تلقائية للخلاصة",
    auto_translate_desc: "عرض المحتوى بلغتي",
    translate_media: "ترجمة الوسائط",
    translate_media_desc: "فيديوهات وقصص عند التوفر",
    content_section: "المحتوى والمجتمع",
    content_section_desc: "أولوية النقاشات والمحتوى المحلي.",
    prefer_debates: "إبراز النقاشات",
    prefer_debates_desc: "الغرف والتصويت أولاً",
    prefer_local: "محتوى منطقتي أولاً",
    prefer_local_desc: "اكتشاف حسب البلد",
    privacy: "الخصوصية والأمان",
    private_profile: "ملف خاص",
    private_profile_desc: "إخفاء من البحث العام",
    block_screenshots: "منع لقطات الشاشة",
    block_screenshots_desc: "Capacitor Android",
    biometric: "البيومترية",
    biometric_desc: "Face ID / بصمة للمحفظة",
    a11y: "إمكانية الوصول",
    large_text: "نص أكبر",
    large_text_desc: "قراءة أسهل",
    reduce_motion: "تقليل الحركة",
    reduce_motion_desc: "انتقالات أقل",
    profile_section: "الملف الشخصي",
    edit_profile: "تعديل الملف",
    save_profile: "حفظ",
    cancel: "إلغاء",
    display_name: "الاسم المعروض",
    flag_emoji: "العلم (رمز تعبيري)",
    bio: "نبذة",
    profile_saved: "✅ تم تحديث الملف",
    profile_error: "❌ تعذر حفظ الملف",
    secure_account: "تأمين حسابي",
    secure_account_desc: "حساب زائر: أضف بريداً أو شبكة اجتماعية.",
    email: "البريد",
    password: "كلمة المرور",
    secure_with_email: "تأمين بهذا البريد",
    link_google: "ربط Google",
    link_facebook: "ربط Facebook",
    login_existing: "تسجيل الدخول لهذا الحساب",
    forgot_password: "نسيت كلمة المرور؟",
    reset_sent: "✅ تم إرسال بريد إعادة التعيين.",
    secure_check_mail: "✅ تحقق من بريدك لتأكيد العنوان.",
    privacy_policy: "سياسة الخصوصية",
    privacy_body:
      "يعالج BAARO البيانات اللازمة للحساب والخلاصة والمحفظة والإشعارات. تُتحقق مبالغ المحفظة من الخادم. يمكنك طلب حذف الحساب.",
    privacy_back: "العودة إلى الإعدادات",
    reset_prefs: "إعادة ضبط التفضيلات",
    reset_confirm: "إعادة كل الإعدادات إلى الافتراضي؟",
    reset_done: "✅ تمت إعادة الضبط",
    export_prefs: "تصدير التفضيلات",
    import_prefs: "استيراد التفضيلات",
    export_done: "✅ تم تنزيل الملف",
    import_done: "✅ تم استيراد التفضيلات",
    import_error: "❌ ملف غير صالح",
    copy_prefs: "نسخ JSON",
    copy_done: "✅ نُسخ إلى الحافظة",
    mfa_section: "المصادقة الثنائية (2FA)",
    mfa_desc: "حالة TOTP / SMS من Supabase Auth.",
    mfa_enabled: "2FA مفعّلة",
    mfa_disabled: "2FA غير مفعّلة",
    mfa_factors: "عامل(عوامل) موثّق",
    mfa_loading: "جارٍ التحقق…",
    mfa_guest: "سجّل بحساب مستقر لإدارة 2FA.",
    lang_partial_hint:
      "اللغات المحلية توجّه المحتوى؛ الواجهة تبقى FR/EN/AR/BM حاليًا.",
    sessions_section: "الجلسات النشطة",
    sessions_desc: "الجهاز الحالي وتسجيل الخروج من كل الأجهزة.",
    session_current: "الجلسة الحالية",
    session_device: "الجهاز",
    session_expires: "تنتهي",
    session_unknown: "غير معروف",
    logout_all: "تسجيل الخروج من كل الأجهزة",
    logout_all_confirm: "تسجيل الخروج من كل الأجهزة؟",
    logout_all_done: "✅ أُغلقت كل الجلسات",
    delete_account: "حذف حسابي",
    delete_account_desc: "إجراء لا رجعة فيه. تُمسح البيانات المحلية.",
    delete_confirm_1: "حذف حساب BAARO نهائيًا؟",
    delete_confirm_2: "تأكيد أخير.",
    delete_done: "✅ تم تسجيل الخروج ومسح البيانات المحلية",
    delete_error: "❌ تعذر حذف الحساب على الخادم",
    replay_onboarding: "إعادة مقدمة BAARO",
    logout: "تسجيل الخروج",
    logout_confirm: "هل تريد حقًا تسجيل الخروج؟",
    guest: "زائر",
    vs_competitors: "مُصمَّم لأفريقيا والأسواق الناشئة",
    version: "الإصدار",
    notifications_section: "الإشعارات",
    notifications_desc: "التحكم في التنبيهات والأصوات وتفضيلات الدفع.",
    sound_settings: "أصوات الإشعارات",
    sound_settings_desc: "مستوى الصوت والتفعيل واختبار الأصوات.",
    performance_section: "الأداء والابتكار",
    performance_desc: "تحكّم في السرعة والبطارية والتحميل المسبق والذاكرة المؤقتة والذكاء المحلي.",
    smart_prefetch: "التحميل المسبق الذكي",
    smart_prefetch_desc: "يحمّل مسبقًا ما قد يكون مفيدًا فقط.",
    battery_saver: "وضع توفير البطارية",
    battery_saver_desc: "يقلّل الحركات والمعالجة في الخلفية.",
    low_bandwidth_mode: "وضع الشبكة الضعيفة",
    low_bandwidth_mode_desc: "يعطي الأولوية للنص ويضغط الوسائط أكثر.",
    local_cache: "ذاكرة مؤقتة محلية ذكية",
    local_cache_desc: "يحتفظ مؤقتًا بالمحتوى المفيد للاستخدام دون اتصال.",
    privacy_ai: "ذكاء اصطناعي خاص افتراضيًا",
    privacy_ai_desc: "يفضّل المعالجة على الجهاز عند توفرها.",
    first_name: "الاسم الأول",
    last_name: "اسم العائلة",
    birth_date: "تاريخ الميلاد",
    location: "الموقع",
    account_email: "بريد الحساب",
    account_phone: "هاتف الحساب",
    registered_country: "بلد التسجيل",
    current_country: "البلد الحالي",
    country_change_wait: "سيصبح تغيير البلد متاحًا بعد 4 أشهر.",
    country_change_ready: "يمكنك تغيير بلدك الحالي.",
    handle_label: "المعرّف",
    choose_country: "اختر بلدًا",
    contacts_links: "جهات الاتصال والروابط",
    lang_beta_hint: "تجريبي: هذه الترجمات قيد المراجعة من قبل متحدثين أصليين، وقد تحتوي بعض النصوص على أخطاء.",
    beta_badge: "تجريبي",
  },
  bm: {
    title: "Sɛbɛnniw",
    subtitle_connected: "Jɛkulu don",
    subtitle_local: "Yɛrɛ yɔrɔ sago",
    search_placeholder: "Sɛbɛnni ɲini…",
    no_results: "Foyi ma sɔrɔ.",
    appearance: "Yɛlɛma",
    theme: "Kɔlɔrɔ",
    theme_midnight: "Su",
    theme_oled: "OLED",
    theme_emerald: "Kɛnɛ",
    language: "Kan",
    region: "Jamana & sara",
    region_desc: "Jamana ani wari Mobile Money ye.",
    country: "Jamana",
    currency: "Wari",
    data_network: "Data & rezo",
    data_network_desc: "2G/3G ye.",
    data_saver: "Data tigɛ",
    data_saver_desc: "Video dɔgɔya",
    autoplay_video: "Video automatiki",
    autoplay_video_desc: "A kɛ ka data mara",
    offline_sync: "Offline fɔlɔ",
    offline_sync_desc: "Kalan ni rezo banna",
    ai_section: "IA regional",
    ai_section_desc: "IA bɛ segin jamana kan.",
    ai_region: "IA yɔrɔ",
    ai_auto: "Automatiki",
    ai_west_africa: "Afrika tilebin",
    ai_global: "Duniya bɛɛ",
    ai_suggest: "IA hakilina",
    ai_suggest_desc: "Sɛbɛnni hakilina",
    translate_section: "Bamanankan kelen",
    translate_section_desc: "Kuma ni video bamanankan na.",
    auto_translate: "Fili automatiki",
    auto_translate_desc: "A yira n ka kan na",
    translate_media: "Video bamanankan",
    translate_media_desc: "Ni a bɛ yen",
    content_section: "Kuma & jɛkulu",
    content_section_desc: "Débat ni jamana kuma.",
    prefer_debates: "Débat fɔlɔ",
    prefer_debates_desc: "Discussion fɔlɔ",
    prefer_local: "Jamana kuma fɔlɔ",
    prefer_local_desc: "I ka jamana",
    privacy: "Gundo & lakana",
    private_profile: "Profil gundo",
    private_profile_desc: "Ɲini kɔnɔ dogo",
    block_screenshots: "Screenshot bali",
    block_screenshots_desc: "Android",
    biometric: "Biométrie",
    biometric_desc: "Bolokɔnighɛsɛ",
    a11y: "Dɔnni nɔgɔya",
    large_text: "Sɛbɛn belebele",
    large_text_desc: "Kalanni nɔgɔya",
    reduce_motion: "Yɛlɛma dɔgɔya",
    reduce_motion_desc: "Animation dɔgɔya",
    profile_section: "Profil",
    edit_profile: "Profil yɛlɛma",
    save_profile: "Mara",
    cancel: "Kassara",
    display_name: "Tɔgɔ",
    flag_emoji: "Jamana taamasiyɛn",
    bio: "I ye mɔgɔ jumɛn ye",
    profile_saved: "✅ Profil mara la",
    profile_error: "❌ Profil ma se ka mara",
    secure_account: "Jɛkulu lakana",
    secure_account_desc: "Email walima Facebook/Google kɛ.",
    email: "Email",
    password: "Secret code",
    secure_with_email: "Email fɛ lakana",
    link_google: "Google kɛ",
    link_facebook: "Facebook kɛ",
    login_existing: "Jɛkulu in na don",
    forgot_password: "Secret code ɲini?",
    reset_sent: "✅ Email ci la",
    secure_check_mail: "✅ I ka email lajɛ",
    privacy_policy: "Gundo sariya",
    privacy_body:
      "BAARO bɛ data kɛ jɛkulu, fili, notifications ye. ",
    privacy_back: "Sɛbɛnniw la segin",
    reset_prefs: "Sago kɔrɔn",
    reset_confirm: "Sago bɛɛ kɔrɔn?",
    reset_done: "✅ Sago kɔrɔnna",
    export_prefs: "Sago bɔ",
    import_prefs: "Sago don",
    export_done: "✅ Fichier telechargé",
    import_done: "✅ Sago don na",
    import_error: "❌ Fichier tɛ ɲɛ",
    copy_prefs: "JSON kopi",
    copy_done: "✅ Kopi kɛra",
    mfa_section: "2FA",
    mfa_desc: "TOTP / SMS Supabase fɛ.",
    mfa_enabled: "2FA sigilen",
    mfa_disabled: "2FA tɛ",
    mfa_factors: "faktor",
    mfa_loading: "Lajɛli…",
    mfa_guest: "Jɛkulu dɔgɔman kɛ 2FA ye.",
    lang_partial_hint: "Kanw bɛ kuma ɲɛsin; UI bɛ FR/EN/AR/BM.",
    sessions_section: "Sessions",
    sessions_desc: "Telefono in ani bɛɛ ka bɔ.",
    session_current: "Session sisan",
    session_device: "Minan",
    session_expires: "A banna",
    session_unknown: "A tɛ dɔn",
    logout_all: "Minan bɛɛ ka bɔ",
    logout_all_confirm: "Minan bɛɛ ka bɔ?",
    logout_all_done: "✅ Sessions bɛɛ datugulen",
    delete_account: "N ka jɛkulu tigɛ",
    delete_account_desc: "A tɛ se ka segin.",
    delete_confirm_1: "Jɛkulu tigɛ fɔlɔfɔlɔ?",
    delete_confirm_2: "A ɲɛnajɛ laban.",
    delete_done: "✅ Bɔra ani data tigɛra",
    delete_error: "❌ Serveur ma se ka tigɛ",
    replay_onboarding: "BAARO fɔlɔ segin",
    logout: "Bɔ",
    logout_confirm: "I b'a fɛ ka bɔ?",
    guest: "Dunan",
    vs_competitors: "A dilannen Afrika ye",
    version: "Version",
    notifications_section: "Kibaru ci",
    notifications_desc: "Kibaru ci, kan ani push sago.",
    sound_settings: "Kibaru ci kan",
    sound_settings_desc: "Kan bonye, sigi, ani kan lajɛ.",
    beta_badge: "bêta",
  },
};

