apply plugin: 'com.android.library'
apply plugin: 'org.jetbrains.kotlin.android'
android {
    namespace "com.baaro.nearby"
    compileSdk 36
    defaultConfig {
        minSdkVersion 24
        targetSdkVersion 36
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }
    kotlinOptions {
        jvmTarget = '21'
    }
}
repositories {
    google()
    mavenCentral()
}
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation project(':capacitor-android')
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation "org.jetbrains.kotlin:kotlin-stdlib:2.0.21"
    implementation 'com.google.android.gms:play-services-nearby:19.3.0'
}
