name: Android Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Référentiel du code (Checkout)
        uses: actions/checkout@v4

      - name: Configurer Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurer le SDK Android
        uses: android-actions/setup-android@v3

      - name: Accepter les licences du SDK Android
        run: yes | sdkmanager --licenses

      - name: Compiler l'application (Gradle)
        run: ./gradlew build
